### PR TITLE
Removed master branch-specific files.

### PR DESCRIPTION
**Pull request by jczimm**

### CODE REVIEW

**Comment by bobbybee** [comment]
A significant part of the website is the Doxygen generated files. While I don't like having the repository at root of the website, the source must be in here _somewhere_ . Thoughts?

**Comment by jczimm** [comment]
`docs/` (previously `html/`) has the doxygen generated files.  And why must the source be in gh-pages?

**Comment by bobbybee** [comment]
@jczimm True, but as CommodityTracking matures, new functions and classes may be introduced; doxygen will likely need to be ran many times in the future. Ideally, we'd have a build script, but temporarily, I'm not certain the former change is necessary.

**Comment by bobbybee** [comment]
I've applied the latter chance; for reasons stated, I'm going to close this PR (at least until we adopt a more stable system).

**Pull request closed without merging**
